### ISSUE TITLE
As a user, I want to be able to join an existing list

### ISSUE THREAD

**Issue by shannonerhea** [the-collab-lab/tcl-65-smart-shopping-list#36]
I believe this feature would also handle issue #34

**Comment by lydiadunning** [comment]
User Flow:
no list token:
  create a new list token -> no confirmation -> create token -> redirect to list
no list token:
  enter list token -> no confirmation -> create token -> redirect to list
existing list token:
  create a new list token -> confirmation -> create token -> redirect to list
existing list token:
  enter list token -> confirmation -> create token -> redirect to list
